import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ScrollButton from "@/components/ScrollButton";
import Footer from "@/components/Footer";
import MobileMenu from "@/components/header/MobileMenu";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <ScrollButton />
        <main>{children}</main>
        <section data-color="black">
          <Footer />
        </section>
      </body>
    </html>
  );
}
